name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "*/5 * * * *"

jobs:
  cypress-smoke:
    name: Run Smoke Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        run: npm install

      - name: Run Smoke Tests
        run: npx cypress run --env TAGS="@smoke" --reporter json --reporter-options reportDir=cypress/reports/json/smoke,reportFilename=results

      - name: Generate Allure Report for Smoke Tests
        if: always()
        run: npx allure generate cypress/reports/json/smoke --clean -o cypress/reports/allure-report-smoke

      - name: Upload Allure Smoke Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-smoke-report
          path: cypress/reports/allure-report-smoke

  cypress-regression:
    name: Run Regression Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        run: npm install

      - name: Run Regression Tests
        run: npx cypress run --env TAGS="@regression" --reporter json --reporter-options reportDir=cypress/reports/json/regression,reportFilename=results

      - name: Generate Allure Report for Regression Tests
        if: always()
        run: npx allure generate cypress/reports/json/regression --clean -o cypress/reports/allure-report-regression

      - name: Upload Allure Regression Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-regression-report
          path: cypress/reports/allure-report-regression

# Akash